name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure docker for gcloud
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image
        env:
          NEXT_PUBLIC_TOSS_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_TOSS_CLIENT_KEY }}
          NEXT_PUBLIC_TOSS_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_TOSS_SECRET_KEY }}
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
        run: |
          docker buildx build --push \
            --build-arg NEXT_PUBLIC_TOSS_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_TOSS_CLIENT_KEY }} \
            --build-arg NEXT_PUBLIC_TOSS_SECRET_KEY=${{ secrets.NEXT_PUBLIC_TOSS_SECRET_KEY }} \
            --build-arg NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }} \
            --tag asia-northeast3-docker.pkg.dev/gcuflow/flow-dev/flow-nextjs-dev:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v4.1.7
        with:
          repository: code-review-platform-flow/flow-manifest
          path: manifests
          token: ${{ secrets.FLOW_DEPLOY_KEY }}

      - name: Update manifest
        run: |
          sed -i "s|image: .*|image: asia-northeast3-docker.pkg.dev/gcuflow/flow-dev/flow-nextjs-dev:${{ github.sha }}|" manifests/flow-web-dev/deployment.yaml

      - name: Commit and push changes
        working-directory: manifests
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update image to asia-northeast3-docker.pkg.dev/gcuflow/flow-dev/flow-nextjs-dev:${{ github.sha }}"
          git push
