name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure docker for gcloud
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --tag asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev/flow-nextjs-dev:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v2
        with:
          repository: code-review-platform-flow/flow-manifest
          path: manifests
          token: ${{ secrets.FLOW_DEPLOY_KEY }}

      - name: List files for debugging
        run: ls -R

      - name: Update manifest
        run: |
          sed -i "s|image: .*|image: asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev:${{ github.sha }}|" manifests/manifests/deployment.yaml

      - name: Commit and push changes
        working-directory: manifests
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update image to asia-northeast3-docker.pkg.dev/code-review-platform-flow/flow-dev:${{ github.sha }}"
          git push
